[package]
name = "lnsocket-core"
version = "0.0.1"
edition = "2021"

[dependencies]
libc = "0.2.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
bindgen = "0.60.1"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"